version: '2'
services:
  redis:
    restart: always
    image: redis:6.2.0
    volumes:
      - redis-db-data:/data
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    command: redis-server --notify-keyspace-events KEA

  backend:
    image: backend
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_SERVER=redis
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SBT_VERSION: "1.8.2"
        SCALA_VERSION: "2.13.10"

volumes:
  redis-db-data: